services:
  marzban-node:
    build: .
#    image: stealthuser/marzban-node:autonomous
    restart: always
    network_mode: host
    container_name: autonomous-node
    environment:
      SSL_CLIENT_CERT_FILE: "/var/lib/marzban-node/ssl_client_cert.pem"
      KEEP_ALIVE_SECONDS: 3600
    volumes:
      - /var/lib/marzban-node:/var/lib/marzban-node
